### ISSUE TITLE
Some icons are missing

### ISSUE THREAD

**Issue by schrodincat** [SublimeText/AFileIcon#5] opened 2019-01-08 18:06 UTC
`editorconfig`, `sublime-project`, `html`, `pug`, `svg`, `less` and `coffee` (there are more probably) icons are missing from sidebar:
<img width="1328" alt="screenshot 2019-01-08 at 21 04 20" src="https://user-images.githubusercontent.com/13354491/50849814-255fe680-1389-11e9-9a6d-58dc0c34236e.png">

**Comment by lkomar** [comment] 2019-01-09 08:10
For me all Icons went missing, not only some. Config files, js files, you name it.

**Comment by lkomar** [comment] 2019-01-09 08:16
Output from the console
```
Traceback (most recent call last):
  File "/snap/sublime-text/38/opt/sublime_text/sublime_plugin.py", line 1007, in run_
    return self.run()
  File "/home/.../.config/sublime-text-3/Installed Packages/A File Icon.sublime-package/core/themes.py", line 189, in run
  File "/home/.../.config/sublime-text-3/Installed Packages/A File Icon.sublime-package/common/utils/icons.py", line 21, in get_missing
  File "/snap/sublime-text/38/opt/sublime_text/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by soifou** [comment] 2019-01-09 09:10
@lkomar same here !

However by removing the package / restart sublime / reinstalling fix the issue for me.

**Comment by lkomar** [comment] 2019-01-09 09:12
I tried that as a first thing even before opening the console, that didn't resolve the issue for me. Let me try to restart my computer alongside, if that fixed the problem for you I'll give it a shot

**Comment by youhunwl** [comment] 2019-01-09 09:14
@lkomar I have the same problem as you. removing the plugin package won't do either.

**Comment by soifou** [comment] 2019-01-09 09:16
If it does not work, try the manual way by cloning this repo directly in `~/.config/sublime-text-3/Packages`

**Comment by youhunwl** [comment] 2019-01-09 09:56
@lkomar I just tried the method you provided and it still doesn't work. Neither online installation nor manual cloning works. 
The online installation control still prompts for the previous error：`resource not found`
Manually clone the console prompt：`error: The settings file "res://Packages/A File Icon/.sublime/A File Icon.sublime-settings" could not be opened`

**Comment by youhunwl** [comment] 2019-01-09 10:39
@lkomar Thank you

**Comment by schrodincat** [comment] 2019-01-09 11:55
I can confirm that cloning repo is working. Interestingly enough if you try to download zip of release and manually copy, like README suggests, it won't work...

**Comment by deathaxe** [comment] 2019-01-09 12:56
*Missing Icons*

While restoring the package, I discovered an issue in ST, which can cause single icons to be missing, if a theme points to a different file name, than defined in A File Icon. This is an issue, which needs to be fixed in ST core. The details can be found at:
https://github.com/SublimeTextIssues/Core/issues/2520

*zzz A File Icon zzz folder*

... is created dynamically by the package and intends to ensure to override theme icons/resources so all files show the icons from this package. 

If you encounter any issues, you can try to run _A File Icon: Revert To Freshly Installed State_ from command palette, which deletes that folder. After a restart of ST it is created again automatically with most up to date content.

I did not double check the plugin's behavior upon update via Package Control though. 

*Package not working when installed via Package Control*

Looks like the `.gitattributes` excludes the required _/common/icons.json_. Will fix that.

**Comment by deathaxe** [comment] 2019-01-09 16:12
Confirmed. It was caused by `export-exclude` a required file. Should be fixed in v3.3.1 which is up at packagecontrol.io now.

**Closed** 2019-01-10 12:49 UTC

**Comment by nadieenespecial** [comment] 2019-04-07 12:40
Removed cache and index, restart, reinstall and nothing. Installed from packagecontrol.
![Screenshot from 2019-04-07 09-35-30](https://user-images.githubusercontent.com/43034851/55683694-ef46ea00-5918-11e9-813e-5723a9879518.png)

**Comment by deathaxe** [comment] 2019-04-07 16:35
No icons are provided for `.browserslistrc` and `site.webmanifest` at the moment.

`.babelrc` and `LICENSE` icons are provided by an alias-syntax. You need to ensure `"aliases": true,` is set (default) in _A File Icons.sublime-settings_

Alias syntaxes, theme patches and icons are dynamically created in _Packages/zzz A File Icon zzz_. So this is a folder to remove as well in case of trouble. It is recreated upon next ST startup then.
