### ISSUE TITLE
"Shell Script (Git).sublime-syntax" warning on startup with Dev Channel ST3.

### ISSUE THREAD

**Issue by leeb** [SublimeText/AFileIcon#8] opened 2019-01-21 15:21 UTC
After updating to ST3 build 3188 (Dev Channel), I have a new warning dialog on startup.

> Error loading syntax file "Packages/zzz A File Icon zzz/aliases/Shell Script (Git).sublime-syntax": 
> Unable to read Packages/zzz A File Icon zzz/aliases/Shell Script (Git).sublime-syntax

Everything seems fine once the dialog is dismissed.

#### Your Environment
macOS High Sierra Version 10.13.6

Console with dev_mode: true

A File Icon: Initializing settings
A File Icon: Initializing icons
         >>> All the necessary icons are provided
A File Icon: Checking theme specific icons
A File Icon: Getting installed themes
         >>> {'Theme - Default': ['Adaptive.sublime-theme', 'Default.sublime-theme']}
A File Icon: Getting the list of theme packages with customization support
         >>> []
A File Icon: Checking aliases
A File Icon: Enabling aliases
         >>> Aliases already enabled
A File Icon: Preparing to patch
A File Icon: Getting installed themes
         >>> {'Theme - Default': ['Adaptive.sublime-theme', 'Default.sublime-theme']}
A File Icon: Getting the list of theme packages with customization support
         >>> []
A File Icon: Getting settings of the icons
         >>> {'opacity_on_hover': 0.5, 'opacity_on_select': 1.0, 'opacity': 0.75, 'row_padding': [], 'size': 8}
A File Icon: Clearing old unnecessary patches
A File Icon: All the themes are already patched

**Comment by deathaxe** [comment] 2019-01-21 16:19
This file is no longer part of the current v3.3.1 release as ST provides support for git files via default _Git Formats_ package.

1. Are you running this latest release?
2. You may try to either manually delete the file or run "A File Icon: Revert to freshly installed state" and restart ST.
3. If the issue persists, you might need to delete the _Cache/zzz A File Icon zzz_ . Maybe an "old" cache of that file still exists, which causes ST to muck.

**Comment by deathaxe** [comment] 2019-01-21 18:37
Maybe the session file or contains any file/view with the syntax still being assigned to for some reason.

**Comment by deathaxe** [comment] 2019-02-02 11:44
I don't intend to write any code which messes with your session file as it might have unpredictable side effects. The issue you see is caused by an unresolved reference in a configuration file of ST, which can happen at any time with any plugin which removes a syntax definition which is in use by ST.

A File Icon removed that syntax as it is no longer needed with the current release ST3176 which provides its own syntax for that purpose.

**Closed by deathaxe** 2019-02-02 11:44 UTC

**Comment by anentropic** [comment] 2019-04-21 14:21
> run "A File Icon: Revert to freshly installed state" and restart ST

> delete the Cache/zzz A File Icon zzz

> Removing syntax references to "zzz A File Icon zzz" in the Sublime session file

none of these worked for me

Every time I re-open ST3 (build 3208) if I look in the file`Sublime Text 3/Local/Session.sublime_session` this line has appeared again (after having deleted it):
```
"syntax": "Packages/zzz A File Icon zzz/aliases/Shell Script (Git).sublime-syntax"
```

Paying more attention to the context I noticed it appears here:
```
"groups":
[
    {
        "sheets":
        [
            {
                "file": "/Users/anentropic/Documents/Dev/project/.gitignore",
                ...
                "settings":
                {
                    ...
                    "settings":
                    {
                        ...
                        "syntax": "Packages/zzz A File Icon zzz/aliases/Shell Script (Git).sublime-syntax"
```

So yeah - I had a file open in one of my Sublime windows, where I must have manually assigned that syntax to it in the past.

After closing that file and restarting ST the annoying alert box is finally gone.

**Comment by Vincent14** [comment] 2020-01-07 09:04
> Removing syntax references to "zzz A File Icon zzz" in the Sublime session file removed the warning dialogs for me.

How did you do that, please?

**Comment by returnchung** [comment] 2020-01-08 09:54
On Mac, close sublime and open the session file as below in the other editor and find all mentioned the `zzz` to delete. And then reopen sublime, everything goes well :).
`$HOME/Library/Application\ Support/Sublime\ Text\ 3/Local/Session.sublime_session`

**Comment by dwhiting10** [comment] 2020-02-08 14:12
Thanks @returnchung this fixed it for me.  On Windows, I found the session file here: `C:\Users\{Your User Name}\AppData\Roaming\Sublime Text 3\Local\Session.sublime_session`

**Comment by GribanovIvan** [comment] 2020-12-06 19:51
i removed zzz A File Icon zzz using package control. Error gone
